spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apitest?characterEncoding=utf-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: flygil
    password: flygil1234